// Строки теста на определение уровня — сняты 1-в-1 из бандла школы
// (scripts/extract-placement.js). Правки контента идут в бандл, потом прогон
// скрипта: руками здесь ничего не меняем.

export const UI = {
  "ru": {
    "title": "JTS — определение уровня английского",
    "pilot": "pilot mode",
    "provisional": "шкала временная, до пилота",
    "next": "Далее",
    "back": "Назад",
    "submit": "Ответить",
    "skip": "Пропустить",
    "startSection": "Начать раздел",
    "finishSection": "Завершить раздел",
    "qOf": "Вопрос {i} из {n}",
    "answeredOf": "Отвечено {a} из {n}",
    "langChoose": "Выберите язык интерфейса",
    "introHint": "Тест занимает примерно 15 минут. Таймера нет — работайте в удобном темпе. Перед каждым разделом будет короткое объяснение.",
    "cando": "Оцените свой английский",
    "candoHint": "Это задаёт стартовую точку теста, а не итоговый уровень.",
    "cando0": "Понимаю лишь отдельные слова",
    "cando1": "Понимаю простые фразы, говорю с трудом",
    "cando2": "Могу объясниться в бытовых ситуациях",
    "cando3": "Свободно общаюсь на большинство тем",
    "cando4": "Работаю или учусь на английском без затруднений",
    "sound": "Проверка звука и видео",
    "soundHint": "Нажмите кнопку — проиграется короткий фрагмент. Проверьте, что видно картинку и слышно речь.",
    "sndAudioTitle": "Проверка звука",
    "sndAudioHint": "Нажмите кнопку и проверьте, слышен ли голос.",
    "sndAllOk": "Вижу и слышу",
    "sndAudioOnly": "Звук есть, видео не видно",
    "sndNoSound": "Звука нет",
    "soundPlay": "▶ Проиграть",
    "soundYes": "Слышу",
    "soundNo": "Звука нет",
    "flag_video_unavailable": "Видео недоступно — раздел «Кино на слух» пропущен.",
    "soundFail": "Аудио недоступно — раздел аудирования будет пропущен, уровень посчитается без него.",
    "blockRouting": "Разминка",
    "blockListening": "Аудирование",
    "blockVocab": "Словарь",
    "blockReading": "Чтение",
    "blockUoe": "Грамматика",
    "blockWriting": "Письмо",
    "blockSpeaking": "Говорение",
    "introRouting": "Шесть быстрых вопросов, чтобы понять, откуда начинать. Выберите один вариант в каждом. Между вопросами можно переходить вперёд и назад, ответы можно менять до завершения раздела.",
    "introListening": "Все вопросы к одной записи собраны на одном экране — отвечайте в любом порядке, ничего не нужно держать в памяти. Запись можно ставить на паузу и перематывать. Число полных прослушиваний ограничено и показано рядом с плеером.",
    "introVocab": "Выберите правильное значение слова. Если слово незнакомо — нажмите «Не знаю»: это честнее и точнее догадки.",
    "introReading": "Прочитайте текст и ответьте на вопросы к нему.",
    "introUoe": "Три типа заданий: 1) впишите в пропуск одно слово (например: «She ___ a doctor» → is); 2) если дано корневое слово — образуйте от него нужную форму (TEACH → teacher); 3) если дано ключевое слово — перестройте фразу, используя его (2–5 слов).",
    "introWriting": "Напишите короткий ответ по заданию. Используйте слова-опоры — они подсказывают нужную конструкцию.",
    "introSpeaking": "Продолжите фразу вслух — 20–30 секунд. Понадобится доступ к микрофону. Произношение на уровень не влияет.",
    "a0Title": "Стартовый блок",
    "a0Note": "Начнём с самого простого: два коротких вопроса. Задания с картинками появятся после пилота.",
    "variantChoose": "Выберите вариант теста",
    "variantExpress": "Быстрый тест",
    "variantExpressT": "≈ 15 минут",
    "variantExpressD": "Ориентировочный общий уровень. Подходит для первого знакомства.",
    "variantFull": "Полный тест",
    "variantFullT": "35–45 минут",
    "variantFullD": "Точнее на границах уровней + отдельный уровень по каждому навыку. С видео и говорением.",
    "blockMinpair": "Различение слов",
    "blockClips": "Кино на слух",
    "introMinpair": "Прозвучит слово (или короткая фраза). Выберите, что именно вы услышали, — из двух похожих вариантов. Слушать можно дважды.",
    "introClips": "Короткие фрагменты из фильмов — одна фраза живой речи. Посмотрите фрагмент и выберите, что было сказано. Просмотров — два на фрагмент.",
    "clipQ": "Что вы услышали?",
    "mpQ": "Что прозвучало?",
    "tfT": "Верно",
    "tfF": "Неверно",
    "tfNS": "Не сказано",
    "tfnsHint": "Отметьте каждое утверждение: верно, неверно или об этом не говорилось.",
    "orderHint": "Нажимайте слова по порядку, чтобы собрать предложение. Нажмите на слово в ответе, чтобы убрать его.",
    "orderSeqHint": "Расставьте события в том порядке, в котором вы их услышали.",
    "orderYour": "Ваш ответ:",
    "reset": "↺ Сбросить",
    "bankfillHint": "Заполните пропуски словами из набора: нажмите слово — оно встанет в первый свободный пропуск. Нажмите на заполненный пропуск, чтобы очистить его.",
    "matchHint": "Соедините пары: нажмите элемент слева, затем его пару справа. Повторное нажатие на пару разъединяет её.",
    "videoMissing": "Видео не найдено. Проверьте, что папка jts-bank/ лежит рядом с файлом теста.",
    "resProfile": "Уровень по навыкам",
    "profListening": "Аудирование",
    "profGrammar": "Грамматика",
    "profReading": "Чтение",
    "skillMinpair": "Различение слов",
    "skillClips": "Кино на слух",
    "skillUoe2": "Интерактивная грамматика",
    "idk": "Не знаю",
    "meaningOf": "Что означает слово",
    "playerReplay": "↻ Ещё раз",
    "playerPause": "⏸ Пауза",
    "playerPlay": "▶ Слушать",
    "listenLeft": "Осталось прослушиваний: ",
    "play": "▶ Слушать",
    "playTts": "▶ Озвучить (синтез речи)",
    "audioMissing": "Файл аудио не найден. Если рядом с тестом нет папки jts-bank/ — положите её туда же, где лежит этот файл.",
    "readText": "Текст (нажмите, чтобы свернуть/развернуть)",
    "hintOneWord": "Впишите одно слово.",
    "hintTransform": "Впишите 2–5 слов с ключевым словом.",
    "typeAnswer": "Впишите ответ…",
    "wformRoot": "Корневое слово: ",
    "transformKw": "Используйте слово: ",
    "writingSupports": "Опоры: ",
    "minWords": "минимум слов: ",
    "micAsk": "Для раздела говорения нужен микрофон.",
    "micAllow": "Разрешить микрофон",
    "rec": "● Идёт запись",
    "recStop": "Стоп",
    "recHint": "Продолжите фразу вслух. Когда закончите — нажмите «Стоп».",
    "recDone": "Записано ✓",
    "teacher": "Режим преподавателя",
    "congratsTitle": "Поздравляем — вы прошли тест! 🎉",
    "congratsLevel": "Ваш текущий уровень",
    "resSe": "Погрешность SE(θ)",
    "resFlags": "Замечания (для преподавателя)",
    "resSkills": "Результаты по разделам",
    "resFeedback": "Мини-фидбэк",
    "advGrammar": "Грамматика: больше всего ошибок — {fams}. Начните повторение именно с этих тем.",
    "advGrammarClean": "Грамматика на вашем уровне чистая — можно смело брать материал на ступень выше.",
    "advListenInf": "В аудировании вы слышите факты, но теряете вывод и отношение говорящего. После каждого диалога задавайте себе вопрос: «зачем он это сказал?»",
    "advListenDet": "В аудировании теряются детали — числа, время, имена. Слушайте короткие записи с задачей выписать 2–3 факта.",
    "advVocab": "Словарный запас уверен примерно до {n} самых частотных слов — дальше рост через тематические подборки и регулярное чтение.",
    "advWriting": "В письменном ответе не прозвучала целевая конструкция задания — отрабатывайте её в коротких письменных ответах по 2–3 предложения.",
    "advNextA": "Ближайшая цель: уверенный Present Simple, вопросы и первые 500 слов — это фундамент всего остального.",
    "advNextA2": "Ближайшая цель: прошедшее время, сравнения и связный рассказ о себе — это выход на самостоятельную речь.",
    "advNextB1": "Ближайшая цель: условные предложения, Present Perfect и спонтанные диалоги без подготовки.",
    "advNextB2": "Ближайшая цель: точность — пассив, инверсия, коллокации и беглость в дискуссии.",
    "advNextC": "Ваш уровень позволяет шлифовать стиль: хеджирование, идиоматика, тексты разных жанров.",
    "advVocabLow": "Начните со словаря: базовые частотные слова дадут самый быстрый видимый прогресс во всех навыках.",
    "fbStrengths": "Ваши сильные стороны: {list}.",
    "fbGrowth": "Стоит уделить внимание: {list} — именно здесь занятия дадут самый быстрый рост.",
    "fbEven": "Ровный, уверенный результат по всем разделам — отличная база для следующего шага!",
    "welcomeTitle": "Мы рады приветствовать вас в школе JTS!",
    "welcomeBody": "Желаем плодотворного и приятного обучения! ✨",
    "resCta": "Продолжить с преподавателем / AI-тьютором",
    "resExport": "Скачать JSON сессии",
    "resUnresolved": "Граница уровня не разрешилась до конца — рекомендуем короткий пробный урок, чтобы уточнить.",
    "devSpeakingWriting": "письменная и устная речь (продукция отстаёт от понимания)",
    "flag_recognition_gap": "Говорение и письмо заметно ниже понимания — рекомендуем разговорную группу, а не уровень выше.",
    "flag_underestimated": "Продукция сильнее, чем показала рецепция, — уровень может быть занижен.",
    "flag_unresolved": "Высокая неопределённость оценки.",
    "flag_speaking_skipped": "Раздел говорения пропущен (нет микрофона).",
    "flag_audio_unavailable": "Аудирование пропущено (нет звука).",
    "flag_a0_branch": "Тест начался со стартового блока A0.",
    "correct": "Верно",
    "wrong": "Неверно",
    "key": "Ключ"
  },
  "kk": {
    "title": "JTS — ағылшын деңгейін анықтау",
    "pilot": "pilot mode",
    "provisional": "шкала уақытша, пилотқа дейін",
    "next": "Әрі қарай",
    "back": "Артқа",
    "submit": "Жауап беру",
    "skip": "Өткізіп жіберу",
    "startSection": "Бөлімді бастау",
    "finishSection": "Бөлімді аяқтау",
    "qOf": "{n} сұрақтың {i}-сі",
    "answeredOf": "{n} сұрақтың {a}-на жауап берілді",
    "langChoose": "Интерфейс тілін таңдаңыз",
    "introHint": "Тест шамамен 15 минут алады. Таймер жоқ — өз қарқыныңызбен өтіңіз. Әр бөлімнің алдында қысқа түсіндірме болады.",
    "cando": "Ағылшыныңызды бағалаңыз",
    "candoHint": "Бұл тесттің бастапқы нүктесі, қорытынды деңгей емес.",
    "cando0": "Тек жеке сөздерді түсінемін",
    "cando1": "Қарапайым сөйлемдерді түсінемін, сөйлеу қиын",
    "cando2": "Тұрмыстық жағдайда түсінісе аламын",
    "cando3": "Көп тақырыпта еркін сөйлесемін",
    "cando4": "Ағылшын тілінде жұмыс істеймін немесе оқимын",
    "sound": "Дыбыс пен видеоны тексеру",
    "soundHint": "Түймені басыңыз — қысқа үзінді ойнатылады. Сурет көрініп, сөз естілетінін тексеріңіз.",
    "sndAudioTitle": "Дыбысты тексеру",
    "sndAudioHint": "Түймені басып, дауыс естілетінін тексеріңіз.",
    "sndAllOk": "Көремін және естимін",
    "sndAudioOnly": "Дыбыс бар, видео көрінбейді",
    "sndNoSound": "Дыбыс жоқ",
    "soundPlay": "▶ Қосу",
    "soundYes": "Естимін",
    "soundNo": "Дыбыс жоқ",
    "flag_video_unavailable": "Видео қолжетімсіз — «Киноны тыңдау» бөлімі өткізілді.",
    "soundFail": "Аудио қолжетімсіз — тыңдалым бөлімі өткізіліп, деңгей онсыз есептеледі.",
    "blockRouting": "Дайындық",
    "blockListening": "Тыңдалым",
    "blockVocab": "Сөздік қор",
    "blockReading": "Оқылым",
    "blockUoe": "Грамматика",
    "blockWriting": "Жазылым",
    "blockSpeaking": "Айтылым",
    "introRouting": "Қайдан бастау керегін анықтайтын алты жылдам сұрақ. Әрқайсысында бір нұсқа таңдаңыз. Сұрақтар арасында алға-артқа жүруге, жауапты бөлім аяқталғанша өзгертуге болады.",
    "introListening": "Бір жазбаға қатысты барлық сұрақ бір экранда — кез келген ретпен жауап беріңіз, ештеңені есте сақтау қажет емес. Жазбаны тоқтатып, айналдыруға болады. Толық тыңдау саны шектеулі, плеердің қасында көрсетілген.",
    "introVocab": "Сөздің дұрыс мағынасын таңдаңыз. Сөз таныс болмаса — «Білмеймін» басыңыз: бұл жорамалдан гөрі дәлірек.",
    "introReading": "Мәтінді оқып, сұрақтарына жауап беріңіз.",
    "introUoe": "Үш түрлі тапсырма: 1) бос орынға бір сөз жазыңыз (мысалы: «She ___ a doctor» → is); 2) түбір сөз берілсе — одан керек форманы жасаңыз (TEACH → teacher); 3) кілт сөз берілсе — сөйлемді сол сөзбен қайта құрыңыз (2–5 сөз).",
    "introWriting": "Тапсырма бойынша қысқа жауап жазыңыз. Тірек сөздерді қолданыңыз — олар керек құрылымды көрсетеді.",
    "introSpeaking": "Сөйлемді дауыстап жалғастырыңыз — 20–30 секунд. Микрофонға рұқсат керек. Дыбысталу деңгейге әсер етпейді.",
    "a0Title": "Бастапқы блок",
    "a0Note": "Ең қарапайымнан бастайық: екі қысқа сұрақ. Суретті тапсырмалар пилоттан кейін қосылады.",
    "variantChoose": "Тест нұсқасын таңдаңыз",
    "variantExpress": "Жылдам тест",
    "variantExpressT": "≈ 15 минут",
    "variantExpressD": "Болжамды жалпы деңгей. Алғашқы танысуға ыңғайлы.",
    "variantFull": "Толық тест",
    "variantFullT": "35–45 минут",
    "variantFullD": "Деңгей шекараларында дәлірек + әр дағды бойынша жеке деңгей. Видео мен айтылым бар.",
    "blockMinpair": "Сөздерді ажырату",
    "blockClips": "Киноны тыңдау",
    "introMinpair": "Бір сөз (немесе қысқа фраза) естіледі. Екі ұқсас нұсқаның қайсысын естігеніңізді таңдаңыз. Екі рет тыңдауға болады.",
    "introClips": "Фильмдерден қысқа үзінділер — тірі сөйлеудің бір фразасы. Үзіндіні көріп, не айтылғанын таңдаңыз. Әр үзіндіні екі рет көруге болады.",
    "clipQ": "Не естідіңіз?",
    "mpQ": "Не айтылды?",
    "tfT": "Дұрыс",
    "tfF": "Қате",
    "tfNS": "Айтылмаған",
    "tfnsHint": "Әр тұжырымды белгілеңіз: дұрыс, қате немесе бұл туралы айтылмаған.",
    "orderHint": "Сөйлем құрау үшін сөздерді ретімен басыңыз. Жауаптағы сөзді алып тастау үшін оны басыңыз.",
    "orderSeqHint": "Оқиғаларды естіген ретіңізбен орналастырыңыз.",
    "orderYour": "Сіздің жауабыңыз:",
    "reset": "↺ Тазарту",
    "bankfillHint": "Бос орындарды жинақтағы сөздермен толтырыңыз: сөзді бассаңыз — ол бірінші бос орынға түседі. Толтырылған орынды тазарту үшін оны басыңыз.",
    "matchHint": "Жұптарды қосыңыз: алдымен сол жақтағы элементті, содан кейін оның оң жақтағы жұбын басыңыз. Жұпты қайта бассаңыз — ажырайды.",
    "videoMissing": "Видео табылмады. jts-bank/ қалтасы тест файлымен қатар тұрғанын тексеріңіз.",
    "resProfile": "Дағдылар бойынша деңгей",
    "profListening": "Тыңдалым",
    "profGrammar": "Грамматика",
    "profReading": "Оқылым",
    "skillMinpair": "Сөздерді ажырату",
    "skillClips": "Киноны тыңдау",
    "skillUoe2": "Интерактивті грамматика",
    "idk": "Білмеймін",
    "meaningOf": "Бұл сөз нені білдіреді",
    "playerReplay": "↻ Қайта тыңдау",
    "playerPause": "⏸ Пауза",
    "playerPlay": "▶ Тыңдау",
    "listenLeft": "Қалған тыңдау саны: ",
    "play": "▶ Тыңдау",
    "playTts": "▶ Дауыстау (синтез)",
    "audioMissing": "Аудио файл табылмады. Тест жанында jts-bank/ қалтасы болмаса — оны осы файлмен бір жерге салыңыз.",
    "readText": "Мәтін (жабу/ашу үшін басыңыз)",
    "hintOneWord": "Бір сөз жазыңыз.",
    "hintTransform": "Кілт сөзбен 2–5 сөз жазыңыз.",
    "typeAnswer": "Жауапты жазыңыз…",
    "wformRoot": "Түбір сөз: ",
    "transformKw": "Мына сөзді қолданыңыз: ",
    "writingSupports": "Тірек сөздер: ",
    "minWords": "ең аз сөз саны: ",
    "micAsk": "Айтылым бөліміне микрофон қажет.",
    "micAllow": "Микрофонға рұқсат беру",
    "rec": "● Жазылып жатыр",
    "recStop": "Тоқтату",
    "recHint": "Сөйлемді дауыстап жалғастырыңыз. Біткенде «Тоқтату» басыңыз.",
    "recDone": "Жазылды ✓",
    "teacher": "Оқытушы режимі",
    "congratsTitle": "Құттықтаймыз — тесті аяқтадыңыз! 🎉",
    "congratsLevel": "Сіздің қазіргі деңгейіңіз",
    "resSe": "Қателік SE(θ)",
    "resFlags": "Ескертпелер (оқытушыға)",
    "resSkills": "Бөлімдер бойынша нәтиже",
    "resFeedback": "Шағын кері байланыс",
    "advGrammar": "Грамматика: қателер көбіне мына тақырыптарда — {fams}. Қайталауды дәл осылардан бастаңыз.",
    "advGrammarClean": "Өз деңгейіңізде грамматика таза — бір саты жоғары материал алуға болады.",
    "advListenInf": "Тыңдалымда фактілерді естисіз, бірақ қорытынды мен сөйлеушінің көзқарасы жоғалады. Әр диалогтан кейін «мұны неге айтты?» деп сұраңыз.",
    "advListenDet": "Тыңдалымда детальдар жоғалады — сандар, уақыт, есімдер. Қысқа жазбаларды 2–3 факт жазып алу мақсатымен тыңдаңыз.",
    "advVocab": "Сөздік қор шамамен ең жиі кездесетін {n} сөзге дейін сенімді — әрі қарай тақырыптық тізімдер мен тұрақты оқу арқылы өсіңіз.",
    "advWriting": "Жазба жауапта тапсырманың мақсатты құрылымы болмады — оны 2–3 сөйлемдік қысқа жауаптармен жаттықтырыңыз.",
    "advNextA": "Жақын мақсат: сенімді Present Simple, сұрақтар және алғашқы 500 сөз — қалғанының бәрі осыған құрылады.",
    "advNextA2": "Жақын мақсат: өткен шақ, салыстыру және өзіңіз туралы байланысты әңгіме.",
    "advNextB1": "Жақын мақсат: шартты сөйлемдер, Present Perfect және дайындықсыз диалогтар.",
    "advNextB2": "Жақын мақсат: дәлдік — пассив, инверсия, коллокациялар және пікірталастағы еркіндік.",
    "advNextC": "Деңгейіңіз стильді шыңдауға мүмкіндік береді: хеджирлеу, идиомалар, әртүрлі жанрдағы мәтіндер.",
    "advVocabLow": "Сөздік қордан бастаңыз: ең жиі кездесетін базалық сөздер барлық дағдыда ең жылдам нәтиже береді.",
    "fbStrengths": "Күшті жақтарыңыз: {list}.",
    "fbGrowth": "Назар аударған жөн: {list} — дәл осы жерде сабақтар ең жылдам нәтиже береді.",
    "fbEven": "Барлық бөлім бойынша біркелкі, сенімді нәтиже — келесі қадамға тамаша негіз!",
    "welcomeTitle": "JTS мектебіне қош келдіңіз!",
    "welcomeBody": "Жемісті әрі жағымды оқу тілейміз! ✨",
    "resCta": "Оқытушымен / AI-тьютормен жалғастыру",
    "resExport": "Сессия JSON жүктеу",
    "resUnresolved": "Деңгей шекарасы толық анықталмады — нақтылау үшін қысқа сынақ сабағын ұсынамыз.",
    "devSpeakingWriting": "жазбаша және ауызша сөйлеу (продукция түсінуден артта)",
    "flag_recognition_gap": "Сөйлеу мен жазу түсінуден төмен — деңгей көтеру емес, сөйлесу тобын ұсынамыз.",
    "flag_underestimated": "Продукция қабылдаудан күшті — деңгей төмен бағалануы мүмкін.",
    "flag_unresolved": "Бағалаудың белгісіздігі жоғары.",
    "flag_speaking_skipped": "Айтылым бөлімі өткізілді (микрофон жоқ).",
    "flag_audio_unavailable": "Тыңдалым өткізілді (дыбыс жоқ).",
    "flag_a0_branch": "Тест A0 бастапқы блогынан басталды.",
    "correct": "Дұрыс",
    "wrong": "Қате",
    "key": "Кілт"
  },
  "en": {
    "title": "JTS — English placement test",
    "pilot": "pilot mode",
    "provisional": "provisional scale (pre-pilot)",
    "next": "Next",
    "back": "Back",
    "submit": "Submit",
    "skip": "Skip",
    "startSection": "Start section",
    "finishSection": "Finish section",
    "qOf": "Question {i} of {n}",
    "answeredOf": "Answered {a} of {n}",
    "langChoose": "Choose interface language",
    "introHint": "The test takes about 15 minutes. There is no timer — go at your own pace. Each section starts with a short explanation.",
    "cando": "Rate your English",
    "candoHint": "This sets the starting point, not your final level.",
    "cando0": "I understand only single words",
    "cando1": "I understand simple phrases, speaking is hard",
    "cando2": "I can get by in everyday situations",
    "cando3": "I communicate freely on most topics",
    "cando4": "I work or study in English with no difficulty",
    "sound": "Sound & video check",
    "soundHint": "Press the button — a short clip will play. Check that you can see the picture and hear the speech.",
    "sndAudioTitle": "Sound check",
    "sndAudioHint": "Press the button and check that you can hear a voice.",
    "sndAllOk": "I see and hear it",
    "sndAudioOnly": "Sound OK, no video",
    "sndNoSound": "No sound",
    "soundPlay": "▶ Play",
    "soundYes": "I hear it",
    "soundNo": "No sound",
    "flag_video_unavailable": "Video unavailable — the “Movie listening” section was skipped.",
    "soundFail": "Audio unavailable — the listening section will be skipped; your level is computed without it.",
    "blockRouting": "Warm-up",
    "blockListening": "Listening",
    "blockVocab": "Vocabulary",
    "blockReading": "Reading",
    "blockUoe": "Grammar",
    "blockWriting": "Writing",
    "blockSpeaking": "Speaking",
    "introRouting": "Six quick questions to find where to start. Pick one option in each. You can move back and forth and change answers until you finish the section.",
    "introListening": "All questions for one recording are on a single screen — answer in any order, nothing to keep in memory. You can pause and seek within the recording. The number of full plays is limited and shown next to the player.",
    "introVocab": "Choose the correct meaning of the word. If you don't know it, press \"I don't know\" — that is more accurate than guessing.",
    "introReading": "Read the text and answer the questions about it.",
    "introUoe": "Three task types: 1) type one word into the gap (e.g. \"She ___ a doctor\" → is); 2) if a root word is given, form the right word from it (TEACH → teacher); 3) if a key word is given, rebuild the phrase using it (2–5 words).",
    "introWriting": "Write a short answer to the task. Use the support words — they hint at the target structure.",
    "introSpeaking": "Continue the phrase aloud for 20–30 seconds. Microphone access is required. Pronunciation does not affect your level.",
    "a0Title": "Starter block",
    "a0Note": "Let's start with the very basics: two short questions. Picture tasks arrive after the pilot.",
    "variantChoose": "Choose your test",
    "variantExpress": "Quick test",
    "variantExpressT": "≈ 15 minutes",
    "variantExpressD": "An approximate overall level. Good for a first look.",
    "variantFull": "Full test",
    "variantFullT": "35–45 minutes",
    "variantFullD": "More precise at level boundaries + a separate level per skill. Includes video and speaking.",
    "blockMinpair": "Hearing the difference",
    "blockClips": "Movie listening",
    "introMinpair": "You will hear a word (or a short phrase). Choose which of two similar options you heard. You can listen twice.",
    "introClips": "Short movie moments — one phrase of real speech. Watch the clip and choose what was said. Two plays per clip.",
    "clipQ": "What did you hear?",
    "mpQ": "What was said?",
    "tfT": "True",
    "tfF": "False",
    "tfNS": "Not stated",
    "tfnsHint": "Mark each statement: true, false, or not mentioned.",
    "orderHint": "Tap the words in order to build the sentence. Tap a word in your answer to remove it.",
    "orderSeqHint": "Put the events in the order you heard them.",
    "orderYour": "Your answer:",
    "reset": "↺ Reset",
    "bankfillHint": "Fill the gaps with words from the bank: tap a word — it goes into the first empty gap. Tap a filled gap to clear it.",
    "matchHint": "Match the pairs: tap an item on the left, then its partner on the right. Tap a matched pair to unlink it.",
    "videoMissing": "Video not found. Check that the jts-bank/ folder sits next to the test file.",
    "resProfile": "Level by skill",
    "profListening": "Listening",
    "profGrammar": "Grammar",
    "profReading": "Reading",
    "skillMinpair": "Hearing the difference",
    "skillClips": "Movie listening",
    "skillUoe2": "Interactive grammar",
    "idk": "I don't know",
    "meaningOf": "What does this word mean",
    "playerReplay": "↻ Play again",
    "playerPause": "⏸ Pause",
    "playerPlay": "▶ Play",
    "listenLeft": "Plays left: ",
    "play": "▶ Play",
    "playTts": "▶ Speak (speech synthesis)",
    "audioMissing": "Audio file not found. If there is no jts-bank/ folder next to the test, place it in the same directory as this file.",
    "readText": "Text (tap to collapse/expand)",
    "hintOneWord": "Type one word.",
    "hintTransform": "Type 2–5 words using the key word.",
    "typeAnswer": "Type your answer…",
    "wformRoot": "Root word: ",
    "transformKw": "Use the word: ",
    "writingSupports": "Support words: ",
    "minWords": "minimum words: ",
    "micAsk": "The speaking section needs a microphone.",
    "micAllow": "Allow microphone",
    "rec": "● Recording",
    "recStop": "Stop",
    "recHint": "Continue the phrase aloud. Press \"Stop\" when you finish.",
    "recDone": "Recorded ✓",
    "teacher": "Teacher mode",
    "congratsTitle": "Congratulations — you finished the test! 🎉",
    "congratsLevel": "Your current level",
    "resSe": "Standard error SE(θ)",
    "resFlags": "Notes (for the teacher)",
    "resSkills": "Results by section",
    "resFeedback": "Quick feedback",
    "advGrammar": "Grammar: most slips were in {fams}. Start your revision exactly there.",
    "advGrammarClean": "Your grammar is clean at this level — you can safely take material one step up.",
    "advListenInf": "In listening you catch the facts but lose the inference and the speaker's attitude. After each dialogue ask yourself: \"why did they say that?\"",
    "advListenDet": "In listening the details slip away — numbers, times, names. Practise with short recordings, writing down 2–3 facts.",
    "advVocab": "Your vocabulary is solid up to roughly the {n} most frequent words — grow it with topic lists and regular reading.",
    "advWriting": "Your written answer missed the target structure of the task — practise it in short 2–3 sentence answers.",
    "advNextA": "Next goal: confident Present Simple, questions and the first 500 words — the foundation for everything else.",
    "advNextA2": "Next goal: past tenses, comparisons and a connected story about yourself.",
    "advNextB1": "Next goal: conditionals, Present Perfect and spontaneous unprepared dialogues.",
    "advNextB2": "Next goal: precision — passive voice, inversion, collocations and fluency in discussion.",
    "advNextC": "Your level lets you polish style: hedging, idiom, writing across genres.",
    "advVocabLow": "Start with vocabulary: high-frequency basic words give the fastest visible progress across all skills.",
    "fbStrengths": "Your strengths: {list}.",
    "fbGrowth": "Worth focusing on: {list} — this is where lessons will pay off fastest.",
    "fbEven": "An even, confident result across all sections — a great base for the next step!",
    "welcomeTitle": "Welcome to JTS school!",
    "welcomeBody": "We wish you productive and enjoyable learning! ✨",
    "resCta": "Continue with a teacher / AI tutor",
    "resExport": "Download session JSON",
    "resUnresolved": "The level boundary did not fully resolve — we recommend a short trial lesson to pin it down.",
    "devSpeakingWriting": "writing and speaking (production lags behind comprehension)",
    "flag_recognition_gap": "Speaking and writing are well below comprehension — we recommend a conversation group, not a higher level.",
    "flag_underestimated": "Production is stronger than reception showed — the level may be underestimated.",
    "flag_unresolved": "High uncertainty of the estimate.",
    "flag_speaking_skipped": "Speaking section skipped (no microphone).",
    "flag_audio_unavailable": "Listening skipped (no sound).",
    "flag_a0_branch": "The test started from the A0 starter block.",
    "correct": "Correct",
    "wrong": "Wrong",
    "key": "Key"
  }
}

export const FAMILY_NAMES = {
  "ru": {
    "tense_aspect": "времена и аспект",
    "modality_condition": "модальные глаголы и условные",
    "articles_determiners": "артикли",
    "quantifiers": "слова количества",
    "prepositions": "предлоги",
    "word_order": "порядок слов",
    "passive_voice": "страдательный залог",
    "relative_clauses": "относительные придаточные",
    "cohesion_linkers": "слова-связки",
    "verb_patterns": "глагольные конструкции",
    "word_form": "словообразование",
    "comparison": "степени сравнения",
    "transform_core": "перестройка фразы",
    "pragmatics": "речевые формулы",
    "lexis": "устойчивые сочетания",
    "cohesion": "связность"
  },
  "kk": {
    "tense_aspect": "шақтар",
    "modality_condition": "модаль етістіктер мен шартты рай",
    "articles_determiners": "артикльдер",
    "quantifiers": "мөлшер сөздері",
    "prepositions": "предлогтар",
    "word_order": "сөз тәртібі",
    "passive_voice": "ырықсыз етіс",
    "relative_clauses": "қатыстық бағыныңқылар",
    "cohesion_linkers": "байланыстырушы сөздер",
    "verb_patterns": "етістік құрылымдары",
    "word_form": "сөзжасам",
    "comparison": "салыстыру шырайлары",
    "transform_core": "сөйлемді қайта құру",
    "pragmatics": "сөйлеу формулалары",
    "lexis": "тұрақты тіркестер",
    "cohesion": "байланыстылық"
  },
  "en": {
    "tense_aspect": "tenses and aspect",
    "modality_condition": "modals and conditionals",
    "articles_determiners": "articles",
    "quantifiers": "quantifiers",
    "prepositions": "prepositions",
    "word_order": "word order",
    "passive_voice": "passive voice",
    "relative_clauses": "relative clauses",
    "cohesion_linkers": "linking words",
    "verb_patterns": "verb patterns",
    "word_form": "word formation",
    "comparison": "comparatives",
    "transform_core": "sentence transformation",
    "pragmatics": "functional phrases",
    "lexis": "collocations",
    "cohesion": "cohesion"
  }
}

export function T(lang, key) {
  const d = UI[lang] || UI.ru
  return key in d ? d[key] : UI.en[key] || key
}
