// Строки движка «Грамматики» — взяты 1-в-1 из грамматика_практика.html
// (I18N — подписи UI урока/упражнений, TLAB — переводы ярлыков заданий).
// Генерируется вручную из источника; при обновлении курса пере-сверить.

export const UI = {
  "ru": {
    "gap_instr": "Дополните предложение",
    "type_ph": "введите предложение…",
    "order_instr": "Расставьте слова в правильном порядке",
    "error_instr": "Нажмите на неправильное слово",
    "match_instr": "Соедините каждый пункт с ответом",
    "timeline_instr": "Когда это происходит?",
    "tl_past": "Прошлое",
    "tl_now": "Сейчас",
    "tl_future": "Будущее",
    "tf_instr": "Нажмите ✓, если по-английски верно, ✗ — если неверно",
    "dictation_instr": "Прослушайте и напишите предложение",
    "dictation_ph": "напишите то, что слышите…",
    "speaking_instr": "Произнесите это предложение вслух",
    "flip_instr": "Нажмите на карточку, чтобы проверить себя",
    "flip_hint": "Переверните → затем подтвердите, что знали",
    "btn_check": "Проверить",
    "btn_continue": "Продолжить →",
    "btn_isaidit": "Я сказал(а) ✓",
    "btn_iknew": "Я знал(а) ✓",
    "btn_next_lesson": "Следующий урок →",
    "btn_back": "Назад к грамматике",
    "fb_correct": "Отлично!",
    "fb_wrong": "Почти!",
    "dlg_notquite": "Не совсем.",
    "dlg_tryother": "Попробуйте другой ответ.",
    "stage1": "① Понять",
    "stage2": "② Построить",
    "stage3": "③ Применить",
    "stage4": "④ Освоить",
    "practice_kick": "Интерактивная практика",
    "practice_title": "Теперь попробуйте вы 💪",
    "practice_desc": "{n} заданий в четырёх этапах — Понять → Построить → Применить → Освоить. Учитесь на практике: после каждого ответа — полное объяснение.",
    "lbl_practice": "Практика",
    "lbl_complete": "Завершено",
    "cel_title": "Урок завершён!",
    "cel_desc": "Отличная работа над темой «{title}»! Вы увидели, поняли и применили это.",
    "cel_score": "✓ {c} / {n} верно",
    "unit": "Раздел",
    "min": "мин"
  },
  "en": {
    "gap_instr": "Complete the sentence",
    "type_ph": "type your sentence…",
    "order_instr": "Put the words in the correct order",
    "error_instr": "Tap the word that is wrong",
    "match_instr": "Match each item to its answer",
    "timeline_instr": "When does this happen?",
    "tl_past": "Past",
    "tl_now": "Now",
    "tl_future": "Future",
    "tf_instr": "Tap ✓ if the English is correct, ✗ if it's wrong",
    "dictation_instr": "Listen and type the sentence",
    "dictation_ph": "type what you hear…",
    "speaking_instr": "Say this sentence out loud",
    "flip_instr": "Tap the card to check yourself",
    "flip_hint": "Flip → then confirm you knew it",
    "btn_check": "Check",
    "btn_continue": "Continue →",
    "btn_isaidit": "I said it ✓",
    "btn_iknew": "I knew it ✓",
    "btn_next_lesson": "Next lesson →",
    "btn_back": "Back to grammar",
    "fb_correct": "Excellent!",
    "fb_wrong": "Almost!",
    "dlg_notquite": "Not quite.",
    "dlg_tryother": "Try the other reply.",
    "stage1": "① Understand",
    "stage2": "② Build",
    "stage3": "③ Apply",
    "stage4": "④ Master",
    "practice_kick": "Interactive practice",
    "practice_title": "Now you try 💪",
    "practice_desc": "{n} activities across four stages — Understand → Build → Apply → Master. Learn by doing, with a full explanation after every answer.",
    "lbl_practice": "Practice",
    "lbl_complete": "Complete",
    "cel_title": "Lesson complete!",
    "cel_desc": "Great work on “{title}”. You've seen it, understood it, and used it.",
    "cel_score": "✓ {c} / {n} correct",
    "unit": "Unit",
    "min": "min"
  },
  "kk": {
    "gap_instr": "Сөйлемді толықтырыңыз",
    "type_ph": "сөйлеміңізді жазыңыз…",
    "order_instr": "Сөздерді дұрыс ретпен қойыңыз",
    "error_instr": "Қате сөзді басыңыз",
    "match_instr": "Әр сұрақты жауабымен сәйкестендіріңіз",
    "timeline_instr": "Бұл қашан болып жатыр?",
    "tl_past": "Өткен",
    "tl_now": "Қазір",
    "tl_future": "Келер",
    "tf_instr": "Ағылшынша дұрыс болса ✓, қате болса ✗ басыңыз",
    "dictation_instr": "Тыңдап, сөйлемді жазыңыз",
    "dictation_ph": "естігеніңізді жазыңыз…",
    "speaking_instr": "Осы сөйлемді дауыстап айтыңыз",
    "flip_instr": "Өзіңізді тексеру үшін картаны басыңыз",
    "flip_hint": "Аударыңыз → содан кейін білгеніңізді растаңыз",
    "btn_check": "Тексеру",
    "btn_continue": "Жалғастыру →",
    "btn_isaidit": "Айттым ✓",
    "btn_iknew": "Білдім ✓",
    "btn_next_lesson": "Келесі сабақ →",
    "btn_back": "Грамматикаға оралу",
    "fb_correct": "Тамаша!",
    "fb_wrong": "Сәл-ақ қалды!",
    "dlg_notquite": "Дәл емес.",
    "dlg_tryother": "Басқа жауапты байқап көріңіз.",
    "stage1": "① Түсіну",
    "stage2": "② Құрастыру",
    "stage3": "③ Қолдану",
    "stage4": "④ Меңгеру",
    "practice_kick": "Интерактивті жаттығу",
    "practice_title": "Енді сіз байқаңыз 💪",
    "practice_desc": "Төрт кезеңге бөлінген {n} тапсырма — Түсіну → Құрастыру → Қолдану → Меңгеру. Әр жауаптан кейін толық түсіндірмемен, істей отырып үйреніңіз.",
    "lbl_practice": "Жаттығу",
    "lbl_complete": "Аяқталды",
    "cel_title": "Сабақ аяқталды!",
    "cel_desc": "«{title}» тақырыбы бойынша жарайсыз! Сіз оны көрдіңіз, түсіндіңіз және қолландыңыз.",
    "cel_score": "✓ {c} / {n} дұрыс",
    "unit": "Бөлім",
    "min": "мин"
  }
}

// Перевод ярлыка задания (typeLabel) на ru/kk; en — как есть.
export const TLAB = {
  "ru": {
    "Find the mistake": "Найдите ошибку",
    "Fill the gap": "Заполните пропуск",
    "Build the sentence": "Составьте предложение",
    "Choose the form": "Выберите форму",
    "Complete": "Дополните",
    "Correct or not?": "Верно или нет?",
    "Guided writing": "Управляемое письмо",
    "Make it negative": "Сделайте отрицательным",
    "Make the question": "Составьте вопрос",
    "Make a question": "Составьте вопрос",
    "Build the question": "Составьте вопрос",
    "Choose the word": "Выберите слово",
    "Write the question": "Напишите вопрос",
    "Choose the preposition": "Выберите предлог",
    "Short answer": "Краткий ответ",
    "Complete the question": "Дополните вопрос",
    "Choose the tense": "Выберите время",
    "Sentence builder": "Конструктор предложений",
    "Match the answers": "Соедините ответы",
    "Choose & write": "Выберите и напишите",
    "Question form": "Форма вопроса",
    "Make the comparative": "Образуйте сравнительную степень",
    "Make the superlative": "Образуйте превосходную степень",
    "Choose the reply": "Выберите ответ",
    "Choose the order": "Выберите порядок",
    "Choose the auxiliary": "Выберите вспомогательный глагол",
    "Which tense?": "Какое время?",
    "Which is correct?": "Что верно?",
    "The -s rule": "Правило -s",
    "Spelling of the -s": "Написание -s",
    "Speed round: correct or not?": "Быстрый раунд: верно или нет?",
    "Positive or negative?": "Утвердительное или отрицательное?",
    "Warm-up": "Разминка",
    "Model sentence": "Образец предложения",
    "Make it 'now'": "Переведите в «сейчас»",
    "Sort the forms": "Распределите формы",
    "Sort the sentences": "Распределите предложения",
    "Natural or not?": "Естественно или нет?",
    "Complete the fact": "Дополните факт",
    "Complete the description": "Дополните описание",
    "Complete the answer": "Дополните ответ",
    "Complete the pattern": "Дополните конструкцию",
    "Complete the tense": "Дополните время",
    "He / She form": "Форма He / She",
    "Position": "Позиция",
    "Past tense": "Прошедшее время",
    "Give the participle": "Дайте причастие",
    "Past necessity": "Прошлая необходимость",
    "Replace with pronouns": "Замените местоимениями",
    "Complete the set": "Дополните набор",
    "Order the adjectives": "Расставьте прилагательные",
    "Order the sentence": "Расставьте предложение",
    "Adjective or adverb?": "Прилагательное или наречие?",
    "Adjective → adverb": "Прилагательное → наречие",
    "Build the phrase": "Составьте словосочетание",
    "Build the reply": "Составьте ответ",
    "Build the offer": "Составьте предложение (offer)",
    "Build the directions": "Составьте маршрут",
    "Build the indirect question": "Составьте косвенный вопрос",
    "Build the reported sentence": "Составьте косвенную речь",
    "Meaning": "Значение",
    "Choose the meaning": "Выберите значение",
    "Give a short answer": "Дайте краткий ответ",
    "Give the short answer": "Дайте краткий ответ",
    "Agree": "Согласитесь",
    "Add a reply question": "Добавьте ответный вопрос",
    "Reply questions": "Ответные вопросы",
    "Report it": "Переведите в косвенную речь",
    "Add the possessive": "Добавьте притяжательное",
    "Rewrite with 's": "Перепишите с 's",
    "Choose the possessive": "Выберите притяжательное",
    "Use a possessive pronoun": "Используйте притяжательное местоимение",
    "Complete the short answer": "Дополните краткий ответ",
    "Match the short answer": "Соедините краткий ответ",
    "Now or usual?": "Сейчас или обычно?",
    "Choose the article": "Выберите артикль",
    "Write the plural": "Напишите множественное число",
    "Make the adverb": "Образуйте наречие",
    "Give the purpose": "Укажите цель",
    "Complete the offer": "Дополните предложение (offer)",
    "Complete the reply": "Дополните ответ",
    "Complete the reply question": "Дополните ответный вопрос",
    "Make it a question": "Сделайте вопросом",
    "Make it past": "Переведите в прошедшее время",
    "Make it passive": "Сделайте страдательным",
    "Make it an imperative": "Сделайте повелительным",
    "Object position": "Место дополнения",
    "Short answer position": "Краткий ответ",
    "Add 's or '": "Добавьте 's или '",
    "Add of if needed": "Добавьте of при необходимости",
    "Add a/an": "Добавьте a/an",
    "Add the adverb": "Добавьте наречие",
    "Certain or possible?": "Точно или возможно?",
    "Prohibition or not necessary?": "Запрет или необязательно?",
    "Sure conclusion": "Уверенный вывод",
    "Ask for advice": "Попросите совет",
    "Give advice": "Дайте совет",
    "Polite request": "Вежливая просьба",
    "Countable or uncountable?": "Исчисляемое или неисчисляемое?",
    "Regular or irregular?": "Правильный или неправильный?",
    "Which one sounds right?": "Что звучит правильно?",
    "Which sounds right?": "Что звучит правильно?",
    "Which form?": "Какая форма?",
    "Which column?": "Какой столбец?",
    "How is the plural formed?": "Как образуется множественное число?",
    "How do we make it negative?": "Как образовать отрицание?",
    "How do we use it?": "Как это использовать?",
    "-ed pronunciation": "Произношение -ed",
    "-ing spelling groups": "Группы написания -ing",
    "Spelling of -ing": "Написание -ing",
    "Listening: type what you hear": "Аудирование: напишите услышанное",
    "Speaking mission": "Речевое задание",
    "Place it in time": "Определите время",
    "Now or in general?": "Сейчас или вообще?",
    "Subject or object question?": "Вопрос к подлежащему или дополнению?"
  },
  "kk": {
    "Find the mistake": "Қатені табыңыз",
    "Fill the gap": "Бос орынды толтырыңыз",
    "Build the sentence": "Сөйлем құрастырыңыз",
    "Choose the form": "Форманы таңдаңыз",
    "Complete": "Толықтырыңыз",
    "Correct or not?": "Дұрыс па, жоқ па?",
    "Guided writing": "Бағытталған жазу",
    "Make it negative": "Болымсыз түрге айналдырыңыз",
    "Make the question": "Сұрақ құрастырыңыз",
    "Make a question": "Сұрақ құрастырыңыз",
    "Build the question": "Сұрақ құрастырыңыз",
    "Choose the word": "Сөзді таңдаңыз",
    "Write the question": "Сұрақты жазыңыз",
    "Choose the preposition": "Предлогты таңдаңыз",
    "Short answer": "Қысқа жауап",
    "Complete the question": "Сұрақты толықтырыңыз",
    "Choose the tense": "Шақты таңдаңыз",
    "Sentence builder": "Сөйлем құрастырғыш",
    "Match the answers": "Жауаптарды сәйкестендіріңіз",
    "Choose & write": "Таңдап, жазыңыз",
    "Question form": "Сұрақ формасы",
    "Make the comparative": "Салыстырмалы шырайды жасаңыз",
    "Make the superlative": "Күшейтпелі шырайды жасаңыз",
    "Choose the reply": "Жауапты таңдаңыз",
    "Choose the order": "Ретті таңдаңыз",
    "Choose the auxiliary": "Көмекші етістікті таңдаңыз",
    "Which tense?": "Қай шақ?",
    "Which is correct?": "Қайсысы дұрыс?",
    "The -s rule": "-s ережесі",
    "Spelling of the -s": "-s жазылуы",
    "Speed round: correct or not?": "Жылдам раунд: дұрыс па, жоқ па?",
    "Positive or negative?": "Болымды ма, болымсыз ба?",
    "Warm-up": "Қыздыру",
    "Model sentence": "Үлгі сөйлем",
    "Make it 'now'": "«Қазір» түріне айналдырыңыз",
    "Sort the forms": "Формаларды сұрыптаңыз",
    "Sort the sentences": "Сөйлемдерді сұрыптаңыз",
    "Natural or not?": "Табиғи ма, жоқ па?",
    "Complete the fact": "Деректі толықтырыңыз",
    "Complete the description": "Сипаттаманы толықтырыңыз",
    "Complete the answer": "Жауапты толықтырыңыз",
    "Complete the pattern": "Үлгіні толықтырыңыз",
    "Complete the tense": "Шақты толықтырыңыз",
    "He / She form": "He / She формасы",
    "Position": "Орналасуы",
    "Past tense": "Өткен шақ",
    "Give the participle": "Есімшені беріңіз",
    "Past necessity": "Өткендегі қажеттілік",
    "Replace with pronouns": "Есімдіктермен ауыстырыңыз",
    "Complete the set": "Жиынды толықтырыңыз",
    "Order the adjectives": "Сын есімдерді ретке қойыңыз",
    "Order the sentence": "Сөйлемді ретке қойыңыз",
    "Adjective or adverb?": "Сын есім бе, үстеу ме?",
    "Adjective → adverb": "Сын есім → үстеу",
    "Build the phrase": "Сөз тіркесін құрастырыңыз",
    "Build the reply": "Жауапты құрастырыңыз",
    "Build the offer": "Ұсынысты құрастырыңыз",
    "Build the directions": "Бағыттарды құрастырыңыз",
    "Build the indirect question": "Жанама сұрақ құрастырыңыз",
    "Build the reported sentence": "Төлеу сөзді құрастырыңыз",
    "Meaning": "Мағынасы",
    "Choose the meaning": "Мағынаны таңдаңыз",
    "Give a short answer": "Қысқа жауап беріңіз",
    "Give the short answer": "Қысқа жауап беріңіз",
    "Agree": "Келісіңіз",
    "Add a reply question": "Жауап-сұрақ қосыңыз",
    "Reply questions": "Жауап-сұрақтар",
    "Report it": "Төлеу сөзге айналдырыңыз",
    "Add the possessive": "Тәуелдікті қосыңыз",
    "Rewrite with 's": "'s арқылы қайта жазыңыз",
    "Choose the possessive": "Тәуелдікті таңдаңыз",
    "Use a possessive pronoun": "Тәуелдік есімдігін қолданыңыз",
    "Complete the short answer": "Қысқа жауапты толықтырыңыз",
    "Match the short answer": "Қысқа жауапты сәйкестендіріңіз",
    "Now or usual?": "Қазір ме, әдетте ме?",
    "Choose the article": "Артикльді таңдаңыз",
    "Write the plural": "Көпше түрін жазыңыз",
    "Make the adverb": "Үстеу жасаңыз",
    "Give the purpose": "Мақсатын көрсетіңіз",
    "Complete the offer": "Ұсынысты толықтырыңыз",
    "Complete the reply": "Жауапты толықтырыңыз",
    "Complete the reply question": "Жауап-сұрақты толықтырыңыз",
    "Make it a question": "Сұраққа айналдырыңыз",
    "Make it past": "Өткен шаққа айналдырыңыз",
    "Make it passive": "Ырықсыз етіске айналдырыңыз",
    "Make it an imperative": "Бұйрық райға айналдырыңыз",
    "Object position": "Толықтауыш орны",
    "Short answer position": "Қысқа жауап",
    "Add 's or '": "'s немесе ' қосыңыз",
    "Add of if needed": "Қажет болса of қосыңыз",
    "Add a/an": "a/an қосыңыз",
    "Add the adverb": "Үстеу қосыңыз",
    "Certain or possible?": "Нақты ма, мүмкін бе?",
    "Prohibition or not necessary?": "Тыйым ба, әлде қажет емес пе?",
    "Sure conclusion": "Нақты қорытынды",
    "Ask for advice": "Кеңес сұраңыз",
    "Give advice": "Кеңес беріңіз",
    "Polite request": "Сыпайы өтініш",
    "Both/either/neither": "both/either/neither",
    "Countable or uncountable?": "Саналатын ба, саналмайтын ба?",
    "Regular or irregular?": "Дұрыс па, бұрыс па?",
    "Which one sounds right?": "Қайсысы дұрыс естіледі?",
    "Which sounds right?": "Қайсысы дұрыс естіледі?",
    "Which form?": "Қай форма?",
    "Which column?": "Қай баған?",
    "How is the plural formed?": "Көпше түрі қалай жасалады?",
    "How do we make it negative?": "Болымсызды қалай жасаймыз?",
    "How do we use it?": "Оны қалай қолданамыз?",
    "-ed pronunciation": "-ed айтылуы",
    "-ing spelling groups": "-ing жазылу топтары",
    "Spelling of -ing": "-ing жазылуы",
    "Listening: type what you hear": "Тыңдау: естігеніңізді жазыңыз",
    "Speaking mission": "Сөйлеу тапсырмасы",
    "Place it in time": "Уақытта орналастырыңыз",
    "Now or in general?": "Қазір ме, жалпы ма?",
    "Subject or object question?": "Бастауыш па, толықтауыш сұрағы ма?"
  }
}

export function uiStr(lang, key) {
  const d = UI[lang] || UI.ru
  return key in d ? d[key] : UI.en[key] || key
}

export function typeLabel(lang, s) {
  if (lang === "en" || !s) return s
  const m = TLAB[lang] || {}
  return s in m ? m[s] : s
}

// Подстановка {placeholders}.
export function fmt(str, map) {
  return String(str || "").replace(/{(w+)}/g, (_, k) => (k in map ? map[k] : ""))
}
