// Данные уроков Shadowing. Перенесены из standalone-тренажёра shadowing.html:
// формат сегмента [start, end, text] и тайминги сохранены точь-в-точь — они уже
// выверены под видео. Английский текст приведён к чистому ASCII (в исходном файле
// типографские кавычки/тире пришли битыми из-за кодировки UTF-8→Latin-1); слова
// и тайминги не менялись. Обложка вычисляется из id ролика YouTube.
//
// short — имя спикера (табы уроков и подпись на карточке). title — полное
// название урока. Названия и английские фразы не локализуются.

const RAW = [
  {
    id: 'sg',
    title: 'Speak Like Selena Gomez',
    short: 'Selena Gomez',
    video: 'jG-4kBIDAzA',
    segments: [
      [0, 16, "Hi guys, how are you?"],
      [16, 23, "So good to see you guys. Are you having a good night?"],
      [23, 33, "I have to say, it's such an honour to be here. I'm so happy to be here. I brought my own speech, but I hope it's OK that I take this opportunity"],
      [33, 39, "to really just spend it with you guys and tell you a little bit about my story."],
      [39, 45, "I'm not an activist. I haven't changed the world or led a campaign. I'm here to"],
      [45, 51, "just tell you my path, so that you can hopefully take something away from it,"],
      [51, 57, "because I don't like being honest with - this is the truth - I don't like being honest with"],
      [57, 64, "press and interviews. I like being honest with you, directly, each and every one of you."],
      [64, 72, "Because I feel like I can. And I'm just going to start with the basics. So, I'm 21, and"],
      [72, 79, "my mom had me when she was 16."],
      [79, 88, "And I'm from Grand Prairie, Texas, and she worked four jobs and completely dedicated her life to making mine better."],
      [88, 97, "So to me, she is the definition of a strong woman. And I love her so much, because she taught me those values."],
      [97, 112, "I have been acting my entire life, and I have known since I was first on Barney - you know, that purple dinosaur - he's great."],
      [112, 118, "You guys are so motivated - I feel like I can say anything!"],
      [118, 124, "The point being: when I was seven, I wanted to be an actress and I wanted to live my dream."],
      [124, 131, "And when I was eleven, a casting director told me that I wasn't strong enough to carry my own show."],
      [131, 143, "And I'm sure all of you have been told that you don't have what it takes, that you may not be good enough - when deep down it's all you want to do."],
      [143, 148, "You want to be a part of something great. You want to make something great."],
      [148, 155, "And it does more than knock the wind out of you - it crushes you when people try to tell you that you're not good enough."],
      [155, 165, "It almost did, for me. But there was my mom, next to me, stronger than ever, and she said the most important thing is to always trust in myself."],
      [165, 173, "If I'm doing something because I love it, I should do it because I love it, and believe that I can do it."],
      [173, 182, "So she told me to keep going. She taught me to turn the other cheek,"],
      [182, 191, "and let the critics be critics, and just trust ourselves."],
      [191, 199, "So, two years later, I got my own show."],
      [199, 209, "And the first thought wasn't, 'that girl said I wouldn't carry my own show - and I did.' I thought about what my mom said."],
      [209, 217, "My mom is like, 'You have to trust yourself.' And I realized that if I didn't believe I could do it, I wouldn't be able to be here."],
      [217, 228, "I live a very blessed life. I have so much to be thankful for, and a lot of you are a big part of inspiring me."],
      [228, 240, "Maybe you're not old enough, but you inspire me to be better - and we should inspire each other to be better."],
      [240, 251, "I'm surrounded by people who are supposed to guide me. Some of them have, and others haven't."],
      [251, 261, "They pressure me. There's so much pressure: you've got to be sexy, you've got to be cute, you've got to be nice, all these things!"],
      [261, 271, "And I'm sure you can all relate - you all have pressure you deal with every day, at school, at work, with friends, with family."],
      [271, 278, "Parents - sometimes mine - they tell me what to wear, how to look, what I should say, how I should be."],
      [278, 286, "Until recently, I had given in to that pressure. I lost sight of who I was."],
      [286, 295, "I listened to the opinions of people, and I tried to change who I am, because I thought others would accept me for it."],
      [295, 302, "And I realized I don't know how to be anything but myself."],
      [302, 313, "And all I really want you to know is that you are changing the world. I'm not changing the world -"],
      [313, 320, "you're changing the world, and that's amazing!"],
      [320, 328, "Please, just be kind to each other, and love and inspire people."],
      [328, 337, "Let's do it - let's change the game!"],
      [337, 343, "The most important thing is that we learn, and we continue to learn from each other."],
      [343, 356, "Please stay true to yourself. Please just remain who you are, and know that we have each other's back - all of us."],
      [356, 371, "I'd be lying if I said I never tried to make myself better by giving in - because I have. But I've learned from my actions, and I'm proudest that I've learned from my mistakes."],
      [371, 380, "I want you to know that I know what it's like - figuring out what types of friends you have. You are who you surround yourself with."],
      [380, 392, "So I just want to say, I hope I can inspire each and every one of you to trust in yourselves, to love and to be loved."],
      [392, 400, "Thank you for allowing me to come up and talk to you guys, because this is such a beautiful thing you're doing."],
      [400, 408, "Be proud of yourselves. This is great!"],
    ],
  },
  {
    id: 'v2',
    title: 'Steve Jobs · Stanford Commencement',
    short: 'Steve Jobs',
    video: '1i9kcBHX2Nw',
    segments: [
      [0, 17, "I am honored to be with you today at your commencement from one of the finest universities"],
      [17, 24, "in the world."],
      [24, 25.89, "I never graduated from college."],
      [25.89, 33, "Truth be told, this is the closest I've ever gotten to a college graduation."],
      [33, 36, "Today I want to tell you three stories from my life."],
      [36, 37.5, "That's it."],
      [37.5, 39.5, "No big deal."],
      [39.5, 46.5, "Just three stories."],
      [46.5, 55.5, "I dropped out of Reed College after the first 6 months, but then stayed around as a drop-in for another 18 months or so before I really quit."],
      [55.5, 58.5, "So why did I drop out?"],
      [58.5, 61.5, "It started before I was born."],
      [61.5, 68.5, "My biological mother was a young, unwed college graduate student, and she decided to put me up for adoption."],
      [68.5, 78.5, "She felt very strongly that I should be adopted by college graduates, so everything was all set for me to be adopted at birth by a lawyer and his wife."],
      [78.5, 84.5, "Except that when I popped out they decided at the last minute that they really wanted a girl."],
      [84.5, 97.5, "So my parents, who were on a waiting list, got a call in the middle of the night asking: 'We have an unexpected baby boy; do you want him?' They said: 'Of course.'"],
      [97.5, 106.5, "My biological mother later found out that my mother had never graduated from college and that my father had never graduated from high school."],
      [106.5, 110.5, "She refused to sign the final adoption papers."],
      [110.5, 121.5, "She only relented a few months later when my parents promised that I would someday go to college."],
      [121.5, 124.5, "And 17 years later I did go to college."],
      [124.5, 135.5, "But I naively chose a college that was almost as expensive as Stanford, and all of my working-class parents' savings were being spent on my college tuition."],
      [135.5, 138.5, "After six months, I couldn't see the value in it."],
      [138.5, 144.5, "I had no idea what I wanted to do with my life and no idea how college was going to help me figure it out."],
      [144.5, 150.5, "And here I was spending all of the money my parents had saved their entire life."],
      [150.5, 155.5, "So I decided to drop out and trust that it would all work out OK."],
      [155.5, 162.5, "It was pretty scary at the time, but looking back it was one of the best decisions I ever made."],
      [162.5, 172.99, "The minute I dropped out I could stop taking the required classes that didn't interest me, and begin dropping in on the ones that looked interesting."],
      [172.99, 174.5, "It wasn't all romantic."],
      [174.5, 190.5, "I didn't have a dorm room, so I slept on the floor in friends' rooms, I returned Coke bottles for the 5-cent deposits to buy food with, and I would walk the 7 miles across town every Sunday night to get one good meal a week at the Hare Krishna temple."],
      [190.5, 192.5, "I loved it."],
      [192.5, 199.5, "And much of what I stumbled into by following my curiosity and intuition turned out to be priceless later on."],
      [199.5, 207.5, "Let me give you one example: Reed College at that time offered perhaps the best calligraphy instruction in the country."],
      [207.5, 214.5, "Throughout the campus every poster, every label on every drawer, was beautifully hand calligraphed."],
      [214.5, 222.5, "Because I had dropped out and didn't have to take the normal classes, I decided to take a calligraphy class to learn how to do this."],
      [222.5, 232.5, "I learned about serif and sans serif typefaces, about varying the amount of space between different letter combinations, about what makes great typography great."],
      [232.5, 241.5, "It was beautiful, historical, artistically subtle in a way that science can't capture, and I found it fascinating."],
      [241.5, 246.5, "None of this had even a hope of any practical application in my life."],
      [246.5, 253.5, "But 10 years later, when we were designing the first Macintosh computer, it all came back to me."],
      [253.5, 256.52, "And we designed it all into the Mac."],
      [256.52, 259.5, "It was the first computer with beautiful typography."],
      [259.5, 267.5, "If I had never dropped in on that single course in college, the Mac would have never had multiple typefaces or proportionally spaced fonts."],
      [267.5, 280.5, "And since Windows just copied the Mac, it's likely that no personal computer would have them."],
      [280.5, 288.5, "If I had never dropped out, I would have never dropped in on this calligraphy class, and personal computers might not have the wonderful typography that they do."],
      [288.5, 293.5, "Of course it was impossible to connect the dots looking forward when I was in college."],
      [293.5, 297.5, "But it was very, very clear looking backward 10 years later."],
      [297.5, 303.5, "Again, you can't connect the dots looking forward; you can only connect them looking backward."],
      [303.5, 307.5, "So you have to trust that the dots will somehow connect in your future."],
      [307.5, 314.5, "You have to trust in something - your gut, destiny, life, karma, whatever."],
      [314.5, 329.5, "This approach has never let me down, and it has made all the difference in my life."],
      [329.5, 335.5, "My second story is about love and loss."],
      [335.5, 339.5, "I was lucky - I found what I loved to do early in life."],
      [339.5, 343.5, "Woz and I started Apple in my parents' garage when I was 20."],
      [343.5, 351.5, "We worked hard, and in 10 years Apple had grown from just the two of us in a garage into a $2 billion company with over 4,000 employees."],
      [351.5, 358.5, "We had just released our finest creation - the Macintosh - a year earlier, and I had just turned 30."],
      [358.5, 360.5, "And then I got fired."],
      [360.5, 364.5, "How can you get fired from a company you started?"],
      [364.5, 373.5, "Well, as Apple grew we hired someone who I thought was very talented to run the company with me, and for the first year or so things went well."],
      [373.5, 377.5, "But then our visions of the future began to diverge and eventually we had a falling out."],
      [377.5, 381.5, "When we did, our Board of Directors sided with him."],
      [381.5, 383.5, "So at 30 I was out."],
      [383.5, 385.01, "And very publicly out."],
      [385.01, 390.5, "What had been the focus of my entire adult life was gone, and it was devastating."],
      [390.5, 393.5, "I really didn't know what to do for a few months."],
      [393.5, 400.5, "I felt that I had let the previous generation of entrepreneurs down - that I had dropped the baton as it was being passed to me."],
      [400.5, 406.5, "I met with David Packard and Bob Noyce and tried to apologize for screwing up so badly."],
      [406.5, 411.5, "I was a very public failure, and I even thought about running away from the valley."],
      [411.5, 417.5, "But something slowly began to dawn on me - I still loved what I did."],
      [417.5, 421.5, "The turn of events at Apple had not changed that one bit."],
      [421.5, 425.5, "I had been rejected, but I was still in love."],
      [425.5, 427.5, "And so I decided to start over."],
      [427.5, 434.5, "I didn't see it then, but it turned out that getting fired from Apple was the best thing that could have ever happened to me."],
      [434.5, 441.5, "The heaviness of being successful was replaced by the lightness of being a beginner again, less sure about everything."],
      [441.5, 444.5, "It freed me to enter one of the most creative periods of my life."],
      [444.5, 452.5, "During the next five years, I started a company named NeXT, another company named Pixar, and fell in love with an amazing woman who would become my wife."],
      [452.5, 463.5, "Pixar went on to create the world's first computer animated feature film, Toy Story, and is now the most successful animation studio in the world."],
      [463.5, 473.5, "In a remarkable turn of events, Apple bought NeXT, I returned to Apple, and the technology we developed at NeXT is at the heart of Apple's current renaissance."],
      [473.5, 477.5, "And Laurene and I have a wonderful family together."],
      [477.5, 482.5, "I'm pretty sure none of this would have happened if I hadn't been fired from Apple."],
      [482.5, 485.5, "It was awful tasting medicine, but I guess the patient needed it."],
      [485.5, 489.27, "Sometimes life hits you in the head with a brick."],
      [489.27, 490.77, "Don't lose faith."],
      [490.77, 497.19, "I'm convinced that the only thing that kept me going was that I loved what I did."],
      [497.19, 499.83, "You've got to find what you love."],
      [499.83, 505.11, "And that is as true for your work as it is for your lovers."],
      [505.11, 516.06, "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work."],
      [516.06, 521.34, "And the only way to do great work is to love what you do."],
      [521.34, 524.36, "If you haven't found it yet, keep looking."],
      [524.36, 525.86, "Don't settle."],
      [525.86, 530.76, "As with all matters of the heart, you'll know when you find it."],
      [530.76, 536.8, "And, like any great relationship, it just gets better and better as the years roll on."],
      [536.8, 539.44, "So keep looking until you find it."],
      [539.44, 540.94, "Don't settle."],
      [540.94, 542.44, "My third story is about death."],
      [542.44, 557.44, "When I was 17, I read a quote that went something like: 'If you live each day as if it was your last, someday you'll most certainly be right.' It made an impression on me, and since then, for the past 33 years, I have looked in the"],
      [557.44, 570.44, "mirror every morning and asked myself: 'If today were the last day of my life, would I want to do what I am about to do today?' And whenever the answer has been 'No' for too many days in a row, I know I need"],
      [570.44, 572.44, "to change something."],
      [572.44, 580.44, "Remembering that I'll be dead soon is the most important tool I've ever encountered to help me make the big choices in life."],
      [580.44, 591.44, "Because almost everything - all external expectations, all pride, all fear of embarrassment or failure - these things just fall away in the face of death, leaving only what is"],
      [591.44, 593.44, "truly important."],
      [593.44, 600.44, "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose."],
      [600.44, 602.44, "You are already naked."],
      [602.44, 606.44, "There is no reason not to follow your heart."],
      [606.44, 610.44, "About a year ago I was diagnosed with cancer."],
      [610.44, 616.44, "I had a scan at 7:30 in the morning, and it clearly showed a tumor on my pancreas."],
      [616.44, 619.44, "I didn't even know what a pancreas was."],
      [619.44, 628.44, "The doctors told me this was almost certainly a type of cancer that is incurable, and that I should expect to live no longer than three to six months."],
      [628.44, 637.44, "My doctor advised me to go home and get my affairs in order, which is doctor's code for prepare to die."],
      [637.44, 645.44, "It means to try to tell your kids everything you thought you'd have the next 10 years to tell them in just a few months."],
      [645.44, 651.44, "It means to make sure everything is buttoned up so that it will be as easy as possible for your family."],
      [651.44, 654.44, "It means to say your goodbyes."],
      [654.44, 657.44, "I lived with that diagnosis all day."],
      [657.44, 669.44, "Later that evening I had a biopsy, where they stuck an endoscope down my throat, through my stomach and into my intestines, put a needle into my pancreas and got a few cells from the tumor."],
      [669.44, 680.44, "I was sedated, but my wife, who was there, told me that when they viewed the cells under a microscope the doctors started crying because it turned out to be a very rare form of pancreatic"],
      [680.44, 682.44, "cancer that is curable with surgery."],
      [682.44, 695.44, "I had the surgery and I'm fine now."],
      [695.44, 701.44, "This was the closest I've been to facing death, and I hope it's the closest I get for a few more decades."],
      [701.44, 712.44, "Having lived through it, I can now say this to you with a bit more certainty than when death was a useful but purely intellectual concept: No one wants to die."],
      [712.44, 717.44, "Even people who want to go to heaven don't want to die to get there."],
      [717.44, 720.44, "And yet death is the destination we all share."],
      [720.44, 723.44, "No one has ever escaped it."],
      [723.44, 729.44, "And that is as it should be, because Death is very likely the single best invention of Life."],
      [729.44, 731.44, "It is Life's change agent."],
      [731.44, 734.44, "It clears out the old to make way for the new."],
      [734.44, 742.44, "Right now the new is you, but someday not too long from now, you will gradually become the old and be cleared away."],
      [742.44, 747.44, "Sorry to be so dramatic, but it is quite true."],
      [747.44, 752.44, "Your time is limited, so don't waste it living someone else's life."],
      [752.44, 758.44, "Don't be trapped by dogma - which is living with the results of other people's thinking."],
      [758.44, 762.44, "Don't let the noise of others' opinions drown out your own inner voice."],
      [762.44, 767.44, "And most important, have the courage to follow your heart and intuition."],
      [767.44, 771.44, "They somehow already know what you truly want to become."],
      [771.44, 785.44, "Everything else is secondary."],
      [785.44, 794.44, "When I was young, there was an amazing publication called The Whole Earth Catalog, which was one of the bibles of my generation."],
      [794.44, 802.44, "It was created by a fellow named Stewart Brand not far from here in Menlo Park, and he brought it to life with his poetic touch."],
      [802.44, 811.44, "This was in the late 1960s, before personal computers and desktop publishing, so it was all made with typewriters, scissors and Polaroid cameras."],
      [811.44, 822.44, "It was sort of like Google in paperback form, 35 years before Google came along: It was idealistic, and overflowing with neat tools and great notions."],
      [822.44, 830.44, "Stewart and his team put out several issues of The Whole Earth Catalog, and then when it had run its course, they put out a final issue."],
      [830.44, 835.44, "It was the mid-1970s, and I was your age."],
      [835.44, 845.44, "On the back cover of their final issue was a photograph of an early morning country road, the kind you might find yourself hitchhiking on if you were so adventurous."],
      [845.44, 849.44, "Beneath it were the words: 'Stay Hungry."],
      [849.44, 854.44, "Stay Foolish.' It was their farewell message as they signed off."],
      [854.44, 855.94, "Stay Hungry."],
      [855.94, 857.94, "Stay Foolish."],
      [857.94, 861.94, "And I have always wished that for myself."],
      [861.94, 866.94, "And now, as you graduate to begin anew, I wish that for you."],
      [866.94, 868.44, "Stay Hungry."],
      [868.44, 870.44, "Stay Foolish."],
      [870.44, 874.44, "Thank you all very much."],
    ],
  },
  {
    id: 'v3',
    title: 'Emma Watson · HeForShe (UN)',
    short: 'Emma Watson',
    video: 'nIwU-9ZTTJc',
    segments: [
      [0, 4.23, "I am reaching out to you because I need your help."],
      [4.23, 10, "We want to end gender inequality - and to do that we need everyone to be involved."],
      [10, 21.54, "This is the first campaign of its kind at the UN: we want to try and galvanize as many men and boys as possible to be advocates for gender equality."],
      [21.54, 27.31, "And we don't just want to talk about it, but make sure it is tangible."],
      [27.31, 41.31, "I was appointed six months ago and the more I have spoken about feminism the more I have realized that fighting for women's rights has too often become synonymous with man-hating."],
      [41.31, 49.31, "If there is one thing I know for certain, it is that this has to stop."],
      [49.31, 62.31, "For the record, feminism by definition is: 'The belief that men and women should have equal rights and opportunities."],
      [62.31, 72.31, "It is the theory of the political, economic and social equality of the sexes.'"],
      [72.31, 80.31, "I started questioning gender-based assumptions when at eight I was confused at being called"],
      [80.31, 90.31, "'bossy,' because I wanted to direct the plays we would put on for our parents - but the boys were not."],
      [90.31, 95.31, "When at 14 I started being sexualized by certain elements of the press."],
      [95.31, 103.31, "When at 15 my girlfriends started dropping out of their sports teams because they didn't"],
      [103.31, 105.81, "want to appear 'muscly.'"],
      [105.81, 113.31, "When at 18 my male friends were unable to express their feelings."],
      [113.31, 119.31, "I decided I was a feminist and this seemed uncomplicated to me."],
      [119.31, 138.31, "But my recent research has shown me that feminism has become an unpopular word."],
      [138.31, 150.31, "Apparently I am among the ranks of women whose expressions are seen as too strong, too aggressive,"],
      [150.31, 158.31, "isolating, anti-men and, unattractive."],
      [158.31, 166.31, "Why is the word such an uncomfortable one?"],
      [166.31, 175.31, "I am from Britain and think it is right that as a woman I am paid the same as my male counterparts."],
      [175.31, 181.31, "I think it is right that I should be able to make decisions about my own body."],
      [181.31, 191.31, "I think it is right that women be involved on my behalf in the policies and decision-making of my country."],
      [191.31, 200.31, "I think it is right that socially I am afforded the same respect as men."],
      [200.31, 213.31, "But sadly I can say that there is no one country in the world where all women can expect to receive these rights."],
      [213.31, 218.31, "No country in the world can yet say they have achieved gender equality."],
      [218.31, 224.46, "These rights I consider to be human rights but I am one of the lucky ones."],
      [224.46, 231.77, "My life is a sheer privilege because my parents didn't love me less because I was born a daughter."],
      [231.77, 236, "My school did not limit me because I was a girl."],
      [236, 243.31, "My mentors didn't assume I would go less far because I might give birth to a child one day."],
      [243.31, 248.69, "These influencers were the gender equality ambassadors that made me who I am today."],
      [248.69, 255.23, "They may not know it, but they are the inadvertent feminists who are changing the world today."],
      [255.23, 257.54, "And we need more of those."],
      [257.54, 266, "And if you still hate the word - it is not the word that is important but the idea and the ambition behind it."],
      [266, 271, "Because not all women have been afforded the same rights that I have."],
      [271, 273.7, "In fact, statistically, very few have been."],
      [273.7, 278.7, "In 1995, Hilary Clinton made a famous speech in Beijing about women's rights."],
      [278.7, 284.08, "Sadly many of the things she wanted to change are still a reality today."],
      [284.08, 291.39, "But what stood out for me the most was that only 30 per cent of her audience were male."],
      [291.39, 300.24, "How can we affect change in the world when only half of it is invited or feel welcome to participate in the conversation?"],
      [300.24, 304.85, "Men - I would like to take this opportunity to extend your formal invitation."],
      [304.85, 307.16, "Gender equality is your issue too."],
      [307.16, 318.31, "Because to date, I've seen my father's role as a parent being valued less by society despite my needing his presence as a child as much as my mother's."],
      [318.31, 336, "I've seen young men suffering from mental illness unable to ask for help for fear it would make them look less 'macho' - in fact in the UK suicide is the biggest killer of men between 20-49 years of age; eclipsing road accidents, cancer and coronary heart disease."],
      [336, 342.15, "I've seen men made fragile and insecure by a distorted sense of what constitutes male success."],
      [342.15, 345.23, "Men don't have the benefits of equality either."],
      [345.23, 358.31, "We don't often talk about men being imprisoned by gender stereotypes but I can see that that they are and that when they are free, things will change for women as a natural consequence."],
      [358.31, 365.62, "If men don't have to be aggressive in order to be accepted women won't feel compelled to be submissive."],
      [365.62, 370.23, "If men don't have to control, women won't have to be controlled."],
      [370.23, 374.08, "Both men and women should feel free to be sensitive."],
      [374.08, 377.93, "Both men and women should feel free to be strong..."],
      [377.93, 384.85, "It is time that we all perceive gender on a spectrum not as two opposing sets of ideals."],
      [384.85, 396.39, "If we stop defining each other by what we are not and start defining ourselves by what we are - we can all be freer and this is what HeForShe is about."],
      [396.39, 397.89, "It's about freedom."],
      [397.89, 400.97, "I want men to take up this mantle."],
      [400.97, 417.89, "So their daughters, sisters and mothers can be free from prejudice but also so that their sons have permission to be vulnerable and human too - reclaim those parts of themselves they abandoned and in doing so be a more true and complete version of themselves."],
      [417.89, 421.74, "You might be thinking who is this Harry Potter girl?"],
      [421.74, 425.97, "And what is she doing up on stage at the UN."],
      [425.97, 431.74, "It's a good question and trust me, I have been asking myself the same thing."],
      [431.74, 435.58, "I don't know if I am qualified to be here."],
      [435.58, 439.43, "All I know is that I care about this problem."],
      [439.43, 442.12, "And I want to make it better."],
      [442.12, 448.66, "And having seen what I've seen - and given the chance - I feel it is my duty to say something."],
      [448.66, 458.66, "English Statesman Edmund Burke said: 'All that is needed for the forces of evil to triumph is for enough good men and women to do nothing.'"],
      [458.66, 467.51, "In my nervousness for this speech and in my moments of doubt I've told myself firmly - if not me, who, if not now, when."],
      [467.51, 474.43, "If you have similar doubts when opportunities are presented to you I hope those words might be helpful."],
      [474.43, 488.38, "Because the reality is that if we do nothing it will take 75 years, or for me to be nearly a hundred before women can expect to be paid the same as men for the same work."],
      [488.38, 489.88, "15."],
      [489.88, 494.78, "5 million girls will be married in the next 16 years as children."],
      [494.78, 503.24, "And at current rates it won't be until 2086 before all rural African girls will be able to receive a secondary education."],
      [503.24, 509.78, "If you believe in equality, you might be one of those inadvertent feminists I spoke of earlier."],
      [509.78, 512.09, "And for this I applaud you."],
      [512.09, 518.63, "We are struggling for a uniting word but the good news is we have a uniting movement."],
      [518.63, 520.17, "It is called HeForShe."],
      [520.17, 527.47, "I am inviting you to step forward, to be seen to speak up, to be the \"he\" for \"she\"."],
      [527.47, 530.55, "And to ask yourself if not me, who?"],
      [530.55, 532.09, "If not now, when?"],
      [532.09, 533.59, "Thank you."],
    ],
  },
  {
    id: 'v4',
    title: 'Oprah Winfrey · Award Speech',
    short: 'Oprah',
    video: 'u1gg_L-syCw',
    segments: [
      [0, 3.6, "Thank you."],
      [3.6, 18, "This is um this is certainly one of"],
      [18, 23.79, "life's full circle moments for me because it's it's so true."],
      [23.79, 28, "Uh we are all beacons of light for"],
      [28, 29, "each other."],
      [29, 36, "And I am grateful that Barbara Walters was there for me to see that beacon of light to become all that"],
      [36, 38.4, "I could be today."],
      [38.4, 40.8, "Thank you, Miss Barbara."],
      [40.8, 42, "Thank you."],
      [42, 46.5, "Um, I want to thank the Harpo family and I want to thank the Kingirl family."],
      [46.5, 51, "I want to thank everybody who has nurtured me, who stood in the gap for me."],
      [51, 58, "Stedman, you're the sweetest man with the greatest integrity."],
      [58, 63.91, "Thank you for helping me to be everything that I am and all that is to come."],
      [63.91, 64.96, "Thank you, Gayle."],
      [64.96, 66, "Thank you, Maya."],
      [66, 67.6, "Thank you all."],
      [67.6, 74, "You know, when I from the beginning, from the beginning, being a"],
      [74, 78.5, "colored, then negro, then black, then African-American child."],
      [78.5, 83, "Uh uh, growing up in Mississippi, my prayer"],
      [83, 85.85, "was for as long as I can remember, God, use me."],
      [85.85, 86.85, "Use me."],
      [86.85, 87.85, "Use this life."],
      [87.85, 91, "I don't know what the future holds for me, but I"],
      [91, 95.54, "know that there is a vision for my life that is greater than my imagination can hold."],
      [95.54, 96.54, "Use me."],
      [96.54, 97.12, "Use me."],
      [97.12, 98.12, "What would you"],
      [98.12, 99.64, "have me to do?"],
      [99.64, 104.55, "And that dream, that desire, that prayer brought me somehow to television."],
      [104.55, 107, "and to be able to use"],
      [107, 115, "this tremendous vehicle of television to go into people's homes and somehow be able to touch their lives and to be the"],
      [115, 123, "beacon that Barbara was for me to be a light of hope and understanding to share some sense of illumination that maybe"],
      [123, 130, "sometimes reflects people's lives and sometimes opens them up to themselves is the greatest blessing God could have"],
      [130, 131, "given me."],
      [131, 136.75, "And I want to continue to use television as we become more polarized in this medium."],
      [136.75, 139, "I choose to use it in"],
      [139, 149, "whatever way I can we can to make people lead better lives to lead them to the highest vision possible for themselves."],
      [149, 150.54, "That is the goal."],
      [150.54, 158, "I thank you for this award because it encourages me to run on and see what the end will be."],
      [158, 159, "Thank you."],
    ],
  },
  {
    id: 'v5',
    title: 'Barack Obama · Victory Speech 2008',
    short: 'Obama',
    video: 'mi8N5gDVpeg',
    segments: [
      [0, 12, "Hello, Chicago."],
      [12, 19.2, "If there is anyone out there who still doubts that America is a place where all things are"],
      [19.2, 28.4, "possible, who still wonders if the dream of our founders is alive in our time, who still questions the power of our democracy,"],
      [28.4, 30, "tonight is your answer."],
      [30, 36, "It's the answer told by lines that stretched around schools and churches in numbers this"],
      [36, 45.2, "nation has never seen, by people who waited three hours and four hours, many for the first time in their lives, because they"],
      [45.2, 50.8, "believed that this time must be different, that their voices could be that difference."],
      [50.8, 56.8, "It's the answer spoken by young and old, rich and poor, Democrat and Republican, black,"],
      [56.8, 61.2, "white, Hispanic, Asian, Native American, gay, straight, disabled and not disabled."],
      [61.2, 67.6, "Americans who sent a message to the world that we have never been just a collection"],
      [67.6, 72, "of individuals or a collection of red states and blue states."],
      [72, 76.4, "We are, and always will be, the United States of America."],
      [76.4, 83.6, "It's the answer that led those who've been told for so long by so many to be cynical"],
      [83.6, 94, "and fearful and doubtful about what we can achieve to put their hands on the arc of history and bend it once more toward the hope"],
      [94, 95.6, "of a better day."],
      [95.6, 102.8, "It's been a long time coming, but tonight, because of what we did on this date in this"],
      [102.8, 106.8, "election at this defining moment change has come to America."],
      [106.8, 110.8, "-- We didn't start with much money or many endorsements."],
      [110.8, 115.4, "Our campaign was not hatched in the halls of Washington."],
      [115.4, 122.2, "It began in the backyards of Des Moines and the living rooms of Concord and the front"],
      [122.2, 123.4, "porches of Charleston."],
      [123.4, 130.6, "It was built by working men and women who dug into what little savings they had to give"],
      [130.6, 133.8, "$5 and $10 and $20 to the cause."],
      [133.8, 139.8, "It grew strength from the young people who rejected the myth of their generation's apathy"],
      [139.8, 146.8, "who left their homes and their families for jobs that offered little pay and less sleep."],
      [146.8, 152.8, "It drew strength from the not-so-young people who braved the bitter cold and scorching heat"],
      [152.8, 161.2, "to knock on doors of perfect strangers, and from the millions of Americans who volunteered and organized and proved"],
      [161.2, 168, "that more than two centuries later a government of the people, by the people, and for the"],
      [168, 171, "people has not perished from the Earth."],
      [171, 172.6, "This is your victory."],
      [172.6, 177.4, "And I know you didn't do this just to win an election."],
      [177.4, 181, "And I know you didn't do it for me."],
      [181, 186.6, "You did it because you understand the enormity of the task that lies ahead."],
      [186.6, 196.2, "For even as we celebrate tonight, we know the challenges that tomorrow will bring are the greatest of our lifetime -- two wars, a"],
      [196.2, 200.2, "planet in peril, the worst financial crisis in a century."],
      [200.2, 207, "Even as we stand here tonight, we know there are brave Americans waking up in the deserts"],
      [207, 212.4, "of Iraq and the mountains of Afghanistan to risk their lives for us."],
      [212.4, 218.8, "There are mothers and fathers who will lie awake after the children fall asleep and wonder"],
      [218.8, 226.8, "how they'll make the mortgage or pay their doctors' bills or save enough for their child's college education."],
      [226.8, 232.8, "There's new energy to harness, new jobs to be created, new schools to build, and threats"],
      [232.8, 236.8, "to meet, alliances to repair."],
      [236.8, 239.8, "The road ahead will be long."],
      [239.8, 242.8, "Our climb will be steep."],
      [242.8, 248, "We may not get there in one year or even in one term."],
      [248, 254, "But, America, I have never been more hopeful than I am tonight that we will get there."],
      [254, 258, "I promise you, we as a people will get there."],
      [258, 275, "There will be setbacks and false starts."],
      [275, 281.2, "There are many who won't agree with every decision or policy I make as president."],
      [281.2, 285.2, "And we know the government can't solve every problem."],
      [285.2, 290.2, "But I will always be honest with you about the challenges we face."],
      [290.2, 294.2, "I will listen to you, especially when we disagree."],
      [294.2, 301.4, "And, above all, I will ask you to join in the work of remaking this nation, the only"],
      [301.4, 311.2, "way it's been done in America for 221 years -- block by block, brick by brick, calloused hand by calloused hand."],
      [311.2, 319.2, "What began 21 months ago in the depths of winter cannot end on this autumn night."],
      [319.2, 322.8, "This victory alone is not the change we seek."],
      [322.8, 326.8, "It is only the chance for us to make that change."],
      [326.8, 332.6, "And that cannot happen if we go back to the way things were."],
      [332.6, 339.6, "It can't happen without you, without a new spirit of service, a new spirit of sacrifice."],
      [339.6, 347.6, "So let us summon a new spirit of patriotism, of responsibility, where each of us resolves"],
      [347.6, 353.8, "to pitch in and work harder and look after not only ourselves but each other."],
      [353.8, 360.2, "Let us remember that, if this financial crisis taught us anything, it's that we cannot have"],
      [360.2, 365.2, "a thriving Wall Street while Main Street suffers."],
      [365.2, 371.2, "In this country, we rise or fall as one nation, as one people."],
      [371.2, 381.8, "Let's resist the temptation to fall back on the same partisanship and pettiness and immaturity that has poisoned our politics for so long."],
      [381.8, 388.6, "Let's remember that it was a man from this state who first carried the banner of the"],
      [388.6, 397.4, "Republican Party to the White House, a party founded on the values of self-reliance and individual liberty and national unity."],
      [397.4, 400.4, "Those are values that we all share."],
      [400.4, 406, "And while the Democratic Party has won a great victory tonight, we do so"],
      [406, 412, "with a measure of humility and determination to heal the divides that have held back our"],
      [412, 413.1, "progress."],
      [413.1, 419.8, "As Lincoln said to a nation far more divided than ours, we are not enemies but friends."],
      [419.8, 425.2, "Though passion may have strained, it must not break our bonds of affection."],
      [425.2, 432.4, "And to those Americans whose support I have yet to earn, I may not have won your vote"],
      [432.4, 434.8, "tonight, but I hear your voices."],
      [434.8, 436.4, "I need your help."],
      [436.4, 439.2, "And I will be your president, too."],
      [439.2, 445.2, "And to all those watching tonight from beyond our shores, from parliaments and palaces to"],
      [445.2, 453.2, "those who are huddled around radios in the forgotten corners of the world, our stories are singular, but our destiny is"],
      [453.2, 459.2, "shared, and a new dawn of American leadership is at hand."],
      [459.2, 465.2, "To those -- to those who would tear the world down: We will defeat you."],
      [465.2, 469.2, "To those who seek peace and security: We support you."],
      [469.2, 474.8, "And to all those who have wondered if America's beacon still burns as bright:"],
      [474.8, 481.2, "Tonight we proved once more that the true strength of our nation comes not from the"],
      [481.2, 486.8, "might of our arms or the scale of our wealth, but from the enduring"],
      [486.8, 491, "power of our ideals: democracy, liberty, opportunity, and unyielding hope."],
      [491, 495, "That's the true genius of America: that America can change."],
      [495, 497, "Our union can be perfected."],
      [497, 503, "What we've already achieved gives us hope for what we can and must achieve tomorrow."],
      [503, 508.6, "This election had many firsts and many stories that will be told for generations."],
      [508.6, 514.2, "But one that's on my mind tonight's about a woman who cast her ballot"],
      [514.2, 515.3, "in Atlanta."],
      [515.3, 526.4, "She's a lot like the millions of others who stood in line to make their voice heard in this election except for one thing: Ann Nixon Cooper is"],
      [526.4, 527.6, "106 years old."],
      [527.6, 534.8, "She was born just a generation past slavery; a time when there were no cars on the road"],
      [534.8, 544.4, "or planes in the sky; when someone like her couldn't vote for two reasons -- because she was a woman and because of the"],
      [544.4, 546, "color of her skin."],
      [546, 552.4, "And tonight, I think about all that she's seen throughout her century in America -- the"],
      [552.4, 561.6, "heartache and the hope; the struggle and the progress; the times we were told that we can't, and the people who pressed on"],
      [561.6, 564.4, "with that American creed: Yes we can."],
      [564.4, 570.8, "At a time when women's voices were silenced and their hopes dismissed, she lived to see"],
      [570.8, 575.2, "them stand up and speak out and reach for the ballot."],
      [575.2, 576.4, "Yes, we can."],
      [576.4, 583.2, "When there was despair in the dust bowl and depression across the land, she saw a nation"],
      [583.2, 589.2, "conquer fear itself with a New Deal, new jobs, a new sense of common purpose."],
      [589.2, 590.4, "Yes, we can."],
      [590.4, 597.2, "When the bombs fell on our harbor and tyranny threatened the world, she was there to witness"],
      [597.2, 601.4, "a generation rise to greatness and a democracy was saved."],
      [601.4, 602.6, "Yes, we can."],
      [602.6, 609, "She was there for the buses in Montgomery, the hoses in Birmingham, a bridge in Selma,"],
      [609, 614.8, "and a preacher from Atlanta who told a people that \"We Shall Overcome.\""],
      [614.8, 616, "Yes, we can."],
      [616, 623.6, "A man touched down on the moon, a wall came down in Berlin, a world was connected by our"],
      [623.6, 625.2, "own science and imagination."],
      [625.2, 632, "And this year, in this election, she touched her finger to a screen, and cast her vote,"],
      [632, 640.8, "because after 106 years in America, through the best of times and the darkest of hours, she knows how America can change."],
      [640.8, 642, "Yes, we can."],
      [642, 644.4, "America, we have come so far."],
      [644.4, 646.4, "We have seen so much."],
      [646.4, 649.6, "But there is so much more to do."],
      [649.6, 660, "So tonight, let us ask ourselves -- if our children should live to see the next century; if my daughters should be so lucky to live"],
      [660, 664.4, "as long as Ann Nixon Cooper, what change will they see?"],
      [664.4, 666.8, "What progress will we have made?"],
      [666.8, 670, "This is our chance to answer that call."],
      [670, 671.6, "This is our moment."],
      [671.6, 678.8, "This is our time, to put our people back to work and open doors of opportunity for our"],
      [678.8, 686.4, "kids; to restore prosperity and promote the cause of peace; to reclaim the American dream and reaffirm that fundamental"],
      [686.4, 692, "truth, that, out of many, we are one; that while we breathe, we hope."],
      [692, 698.8, "And where we are met with cynicism and doubts and those who tell us that we can't,"],
      [698.8, 708.2, "we will respond with that timeless creed that sums up the spirit of a people: Yes, we can."],
    ],
  },
]

// Обложка ролика — превью YouTube. Берём mqdefault (320×180): это ЧЕСТНЫЙ 16:9
// без чёрных полос и есть у всех роликов. hqdefault (480×360) — 4:3 с
// letterbox'ом, из-за которого обложки кропались по-разному и одна «вылезала».
// maxresdefault красивее, но есть не у всех (у Обамы 404).
export const LESSONS = RAW.map((lesson) => ({
  ...lesson,
  cover: `https://i.ytimg.com/vi/${lesson.video}/mqdefault.jpg`,
}))

// Урок по id; фолбэк на первый — чтобы битый диплинк не ронял экран.
export function getLesson(id) {
  return LESSONS.find((l) => l.id === id) || LESSONS[0]
}
