// Мета уровней воркбуков (standalone HTML в public/practice/workbooks/).
// theme — индекс палитры gr-cover[data-th] (fallback, если постер не загрузился).
// poster — обложка в public/practice/workbooks/covers/.
// min — ориентир по времени (≈ уроки × 10 мин), для бейджа ⏱ как у GrammarCard.
export const WORKBOOK_LEVELS = [
  {
    code: 'a0',
    label: 'A0',
    desc: 'Starter',
    title: 'Let’s start speaking English',
    tag: 'STARTER WORKBOOK',
    units: 7,
    lessons: 24,
    theme: '4',
    min: 240,
    poster: '/practice/workbooks/covers/a0.webp',
  },
  {
    code: 'a1',
    label: 'A1',
    desc: 'Beginner',
    title: 'Back in time',
    tag: 'BEGINNER WORKBOOK',
    units: 8,
    lessons: 32,
    theme: '0',
    min: 320,
    poster: '/practice/workbooks/covers/a1.webp',
  },
  {
    code: 'a2',
    label: 'A2',
    desc: 'Elementary',
    title: 'Daily life',
    tag: 'ELEMENTARY WORKBOOK',
    units: 12,
    lessons: 36,
    theme: '6',
    min: 360,
    poster: '/practice/workbooks/covers/a2.webp',
  },
  {
    code: 'b1',
    label: 'B1',
    desc: 'Intermediate',
    title: 'Friends and money',
    tag: 'INTERMEDIATE WORKBOOK',
    units: 12,
    lessons: 36,
    theme: '2',
    min: 360,
    poster: '/practice/workbooks/covers/b1.webp',
  },
  {
    code: 'b2',
    label: 'B2',
    desc: 'Upper-Intermediate',
    title: 'Making Contact',
    tag: 'UPPER-INTERMEDIATE',
    units: 12,
    lessons: 48,
    theme: '5',
    min: 480,
    poster: '/practice/workbooks/covers/b2.webp',
  },
]
